### ISSUE TITLE
broken in webui dev branch and add extension to index

### ISSUE THREAD

**Issue by w-e-w** [huchenlei/sd-webui-api-payload-display#10]
two things
### adding extension index
I was made aware of this extension by a [comment](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14057#issuecomment-1823683446) so I want to add it the index

please check if this looks okay to you https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/234

---

### broken in webui dev branch
one thing that I do before adding an extension is I will test the extension

what I found out is that it seems the extension is broken in the [current dev branch](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/8aa51f682c17d85f4585b9471860224568d25e95) but working in 1.6.1 master
with my very limited JavaScript experience I believe the issue is due to your `MutationObserver` not firing https://github.com/huchenlei/sd-webui-api-payload-display/blob/cae439ed88acefc5bf301d251a5ef68b5475f2c4/javascript/api_payload_display.js#L84

since the dev branch is changing I'm not sure if this issue would be fixed automatically in the future, but I think making you aware of the issue before hand might be good

**Comment by huchenlei** [comment]
I think the issue is a DOM structure change that renders the new progress element under `#txt2img_results_panel` instead of `#txt2img_results`. I will submit a fix later.

**Comment by w-e-w** [comment]
> I think the issue is a DOM structure change that renders the new progress element under `#txt2img_results_panel` instead of `#txt2img_results`. I will submit a fix later.

I would hold on a bit not sure what AUTO would do
see https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14068
my guess is that if we move gradio 4.0+ more things will break

**Comment by huchenlei** [comment]
Temp fix submitted https://github.com/huchenlei/sd-webui-api-payload-display/commit/3db2b44b56843ce124066f08f24240211d589afd. I will keep an eye on A1111 changes to gradio 4.0.
