### ISSUE TITLE
No proper documentation

### ISSUE THREAD

**Issue by RaidenRadec** [huchenlei/sd-webui-api-payload-display#4]
I dont see a way to use the extension , there is no proper documentation or wiki on how to use it

**Comment by huchenlei** [comment]
You do any generation in WebUI (txt2img/img2img), after the generation completes, you should see content in the extension accordion.

**Comment by RaidenRadec** [comment]
Ok so I should place it in the extensions folder in sd webui is it and
after every generations I will see that
