### ISSUE TITLE
Cannot read properties of undefined (reading 'writeText')

### ISSUE THREAD

**Issue by MatoMA** [huchenlei/sd-webui-api-payload-display#6]
"Failed to copy" unless i follow this tutorial to config my Chrome:
https://bobbyhadz.com/blog/navigator-clipboard-is-undefined-in-javascript

The error msg: Cannot read properties of undefined (reading 'writeText')

**Comment by huchenlei** [comment]
Clipboard API not available explicitly specified in the error message now.
