### ISSUE TITLE
Cannot copy the payload  

### ISSUE THREAD

**Issue by khitran-AB** [huchenlei/sd-webui-api-payload-display#7]
When tried to copy the payload through "copy" button, it fails
![Screenshot from 2023-08-07 14-29-57](https://github.com/huchenlei/sd-webui-api-payload-display/assets/77095042/f50eaf14-f8b4-4c63-ac8a-9cd40c000fcc)

**Comment by huchenlei** [comment]
See https://github.com/huchenlei/sd-webui-api-payload-display/issues/6. Please confirm the console messages. Very likely the clipboard api is not available.
